require("plugins.install_packer")
require("plugins.startup")

local config = require("plugins.config")

config.auto_session()
config.fzf()
config.fzf_checkout()
config.harpoon()
config.hop()
config.indent_blankline()
config.lualine()
config.nvim_autopairs()
--config.nvim_cmp()
config.nvim_fzf()
--config.nvim_lsp_installer()
config.nvim_treesitter()
--config.onedark()
config.rnvimr()
config.tokyonight()
config.gitsigns()
--config.nvim_lspconfig()
config.lsp_zero()
config.null_ls()
config.undotree()
