local package_manager = require("plugins.lazy")
local config = require("plugins.config")

package_manager.bootstrap()
package_manager.install_plugins()

config.rnvimr()
config.fzf()
config.fzf_checkout()
config.nvim_fzf()
config.gitsigns()
config.auto_session()
config.undotree()
config.indent_blankline()
config.lualine()
config.nvim_treesitter_new()
config.tokyonight()
config.rustaceanvim()
config.nvim_autopairs()
config.luasnip()
require("plugins.lsp_setup")
config.null_ls()

-- DEPRECATED/DEAD/OLD
--config.hop()
--config.tailwind_tools()
--config.nvim_treesitter()
